# Exercise - part 1

In [2]:
import numpy as np

Create a 20x3 array of random numbers between 0 and 1 – call it `arr`.

In [3]:
arr = np.random.rand(20, 3)
arr

array([[0.97477599, 0.14647699, 0.26019015],
       [0.52058749, 0.4059435 , 0.18698041],
       [0.20358058, 0.08090661, 0.54455864],
       [0.76544148, 0.04631739, 0.30526112],
       [0.53585359, 0.74058872, 0.46283218],
       [0.6280526 , 0.58633176, 0.62078185],
       [0.78223201, 0.87841733, 0.73904255],
       [0.6603572 , 0.390251  , 0.19358918],
       [0.0518332 , 0.4856924 , 0.94851254],
       [0.92927088, 0.12747082, 0.26023432],
       [0.93754133, 0.64542901, 0.46590117],
       [0.57973341, 0.26699052, 0.57994116],
       [0.05316318, 0.07227389, 0.05320115],
       [0.17344121, 0.76517341, 0.09825695],
       [0.82071542, 0.86555616, 0.06839626],
       [0.42668527, 0.10996731, 0.08389588],
       [0.31497562, 0.79039738, 0.75554875],
       [0.57933754, 0.55416808, 0.37367075],
       [0.34656961, 0.44243888, 0.17084415],
       [0.87913536, 0.73223044, 0.78174946]])

Select all rows and the first two columns.

In [5]:
arr[:, :2]

array([[0.97477599, 0.14647699],
       [0.52058749, 0.4059435 ],
       [0.20358058, 0.08090661],
       [0.76544148, 0.04631739],
       [0.53585359, 0.74058872],
       [0.6280526 , 0.58633176],
       [0.78223201, 0.87841733],
       [0.6603572 , 0.390251  ],
       [0.0518332 , 0.4856924 ],
       [0.92927088, 0.12747082],
       [0.93754133, 0.64542901],
       [0.57973341, 0.26699052],
       [0.05316318, 0.07227389],
       [0.17344121, 0.76517341],
       [0.82071542, 0.86555616],
       [0.42668527, 0.10996731],
       [0.31497562, 0.79039738],
       [0.57933754, 0.55416808],
       [0.34656961, 0.44243888],
       [0.87913536, 0.73223044]])

Select the first two rows and the last two columns.

In [10]:
arr[:2,-2:]

array([[0.14647699, 0.26019015],
       [0.4059435 , 0.18698041]])

Create a 2D array from `[[1, 2, 3], [4, 5, 6], [7, 8, 9]]` - call it `arr2`.

In [6]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Determine the dimensions of `arr2`.

In [11]:
arr2.shape

(3, 3)

Take the last column of `arr2` and store it in a variable called `col`.

In [16]:
col = arr2[:,-1]
col

array([3, 6, 9])

Identify the elements of `col` that are greater than 5.

In [17]:
col[col>5]

array([6, 9])

# Exercise - part 2

Load the `counts.npy` file into a numpy array called `counts`. This file contains gene counts for 5 samples across all genes in the genome.

In [35]:
counts = np.load("counts.npy")
print(counts)
counts.shape

[[  6  86   0 ...   0   0   0]
 [  8 105   0 ...   0   0   0]
 [  8  93   0 ...   0   0   0]
 [  8 102   0 ...   0   0   0]
 [  6 135   0 ...   0   0   0]]


(5, 23710)

Ensure the counts are in the correct format (rows = genes, columns = samples).

In [36]:
counts = np.transpose(counts)
counts

array([[  6,   8,   8,   8,   6],
       [ 86, 105,  93, 102, 135],
       [  0,   0,   0,   0,   0],
       ...,
       [  0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0]])

Remove all genes with a count of less than 10 across all samples call this `counts_filtered`.

In [37]:
counts_filtered = counts[counts.sum(axis=1)>=10, :]
counts_filtered

array([[   6,    8,    8,    8,    6],
       [  86,  105,   93,  102,  135],
       [  72,   73,   69,   26,   62],
       ...,
       [   1,    1,    8,    2,    1],
       [   3,    4,    1,    1,    1],
       [ 953, 1126,   27,   46,   21]])

CPM (Counts Per Million) normalise the data (divide each value by the total count for that sample and multiply by 1 million). Call this `counts_cpm`.

In [31]:
counts_cpm = counts_filtered/(counts_filtered.sum(axis=0))*1000000
counts_cpm

array([[9.44093460e-01, 1.09949797e+00, 1.12746785e+00, 8.88032530e-01,
        8.03803599e-01],
       [1.35320063e+01, 1.44309108e+01, 1.31068138e+01, 1.13224148e+01,
        1.80855810e+01],
       [1.13291215e+01, 1.00329190e+01, 9.72441021e+00, 2.88610572e+00,
        8.30597052e+00],
       ...,
       [1.57348910e-01, 1.37437246e-01, 1.12746785e+00, 2.22008132e-01,
        1.33967266e-01],
       [4.72046730e-01, 5.49748985e-01, 1.40933481e-01, 1.11004066e-01,
        1.33967266e-01],
       [1.49953511e+02, 1.54754339e+02, 3.80520400e+00, 5.10618704e+00,
        2.81331260e+00]])

Add a pseudo count of 1 to each value in `counts_cpm` and take the log2 of the resulting values. Call this `counts_log2`.


In [33]:
counts_log2 = np.log2(counts_cpm+1)
counts_log2

array([[0.95909758, 1.07004439, 1.08913733, 0.91688362, 0.85104226],
       [3.86116199, 3.94775132, 3.81832027, 3.6232131 , 4.2544112 ],
       [3.6239981 , 3.46374263, 3.4228264 , 1.95832515, 3.21815662],
       ...,
       [0.21082386, 0.18578695, 1.08913733, 0.28925389, 0.181379  ],
       [0.55782347, 0.63203456, 0.19021468, 0.1518641 , 0.181379  ],
       [7.2379605 , 7.28312855, 2.26459768, 2.61027178, 1.9310448 ]])